// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWPoKj-EW0kYKCzevEbxsWx0QvIhytu-I',
    appId: '1:250215078466:web:70128423439ae977782bdb',
    messagingSenderId: '250215078466',
    projectId: 'movies-app-1999',
    authDomain: 'movies-app-1999.firebaseapp.com',
    storageBucket: 'movies-app-1999.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4_VwiW9Fe5fcOw5kWUpJDMUN2cJaQJMw',
    appId: '1:250215078466:android:bb84ac2ace577763782bdb',
    messagingSenderId: '250215078466',
    projectId: 'movies-app-1999',
    storageBucket: 'movies-app-1999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDSsBwlKgJCXKP7__7nLLRCXVrGhnH4qk',
    appId: '1:250215078466:ios:6f60e6d4002fab53782bdb',
    messagingSenderId: '250215078466',
    projectId: 'movies-app-1999',
    storageBucket: 'movies-app-1999.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDSsBwlKgJCXKP7__7nLLRCXVrGhnH4qk',
    appId: '1:250215078466:ios:6f60e6d4002fab53782bdb',
    messagingSenderId: '250215078466',
    projectId: 'movies-app-1999',
    storageBucket: 'movies-app-1999.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWPoKj-EW0kYKCzevEbxsWx0QvIhytu-I',
    appId: '1:250215078466:web:72590120738cbe73782bdb',
    messagingSenderId: '250215078466',
    projectId: 'movies-app-1999',
    authDomain: 'movies-app-1999.firebaseapp.com',
    storageBucket: 'movies-app-1999.firebasestorage.app',
  );
}
